# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations

FORWARDS_SQL = """
DO $$
DECLARE
  r record;
  new_name text;
BEGIN
  -- Drop temporary compatibility views created during the transition.
  FOR r IN
    SELECT viewname
    FROM pg_views
    WHERE schemaname = 'public'
      AND viewname LIKE 'gridstream_%'
  LOOP
    EXECUTE format('DROP VIEW IF EXISTS %I;', r.viewname);
  END LOOP;

  -- Rename legacy redzone_* tables to gridstream_*.
  FOR r IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename LIKE 'redzone_%'
    ORDER BY tablename
  LOOP
    new_name := replace(r.tablename, 'redzone_', 'gridstream_');
    IF EXISTS (
      SELECT 1
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relname = new_name
    ) THEN
      RAISE NOTICE 'relation % already exists; skipping table rename', new_name;
    ELSE
      EXECUTE format('ALTER TABLE %I RENAME TO %I;', r.tablename, new_name);
    END IF;
  END LOOP;

  -- Rename legacy sequences to match new table names.
  FOR r IN
    SELECT c.relname AS seq_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'S'
      AND c.relname LIKE 'redzone_%'
  LOOP
    new_name := replace(r.seq_name, 'redzone_', 'gridstream_');
    IF EXISTS (
      SELECT 1
      FROM pg_class c2
      JOIN pg_namespace n2 ON n2.oid = c2.relnamespace
      WHERE n2.nspname = 'public'
        AND c2.relname = new_name
    ) THEN
      RAISE NOTICE 'relation % already exists; skipping sequence rename', new_name;
    ELSE
      EXECUTE format('ALTER SEQUENCE %I RENAME TO %I;', r.seq_name, new_name);
    END IF;
  END LOOP;
END $$;
"""


REVERSE_SQL = """
DO $$
DECLARE
  r record;
  old_name text;
BEGIN
  -- Rename gridstream_* tables back to redzone_*.
  FOR r IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename LIKE 'gridstream_%'
    ORDER BY tablename
  LOOP
    old_name := replace(r.tablename, 'gridstream_', 'redzone_');
    IF EXISTS (
      SELECT 1
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relname = old_name
    ) THEN
      RAISE NOTICE 'relation % already exists; skipping table rename', old_name;
    ELSE
      EXECUTE format('ALTER TABLE %I RENAME TO %I;', r.tablename, old_name);
    END IF;
  END LOOP;

  -- Rename gridstream_* sequences back to redzone_*.
  FOR r IN
    SELECT c.relname AS seq_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'S'
      AND c.relname LIKE 'gridstream_%'
  LOOP
    old_name := replace(r.seq_name, 'gridstream_', 'redzone_');
    IF EXISTS (
      SELECT 1
      FROM pg_class c2
      JOIN pg_namespace n2 ON n2.oid = c2.relnamespace
      WHERE n2.nspname = 'public'
        AND c2.relname = old_name
    ) THEN
      RAISE NOTICE 'relation % already exists; skipping sequence rename', old_name;
    ELSE
      EXECUTE format('ALTER SEQUENCE %I RENAME TO %I;', r.seq_name, old_name);
    END IF;
  END LOOP;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0002_gamehashtag_newssource_playercollegehistory_and_more"),
    ]

    operations = [
        migrations.RunSQL(FORWARDS_SQL, REVERSE_SQL),
    ]
