# Generated by Django 5.2.11 on 2026-02-23

from django.db import migrations

FORWARDS_SQL = """
CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw.raw_ingest_batch (
    id BIGSERIAL PRIMARY KEY,
    source_system TEXT NOT NULL,
    dataset_name TEXT NOT NULL,
    source_url TEXT,
    source_file TEXT,
    source_version TEXT,
    source_checksum TEXT,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    row_count INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS raw_ingest_batch_src_ds_loaded_idx
    ON raw.raw_ingest_batch (source_system, dataset_name, loaded_at DESC);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_pbp (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    game_id TEXT NOT NULL,
    play_id TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    posteam TEXT,
    defteam TEXT,
    source_row_number INTEGER,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_batch_idx
    ON raw.raw_nflverse_pbp (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_game_play_idx
    ON raw.raw_nflverse_pbp (game_id, play_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_season_week_idx
    ON raw.raw_nflverse_pbp (season, week);
CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_payload_gin_idx
    ON raw.raw_nflverse_pbp USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_player_stats (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    week INTEGER,
    game_id TEXT,
    player_id TEXT,
    player_name TEXT,
    team TEXT,
    opponent TEXT,
    position TEXT,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_player_stats_batch_idx
    ON raw.raw_nflverse_player_stats (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_player_stats_season_week_idx
    ON raw.raw_nflverse_player_stats (season, week);
CREATE INDEX IF NOT EXISTS raw_nflverse_player_stats_game_player_idx
    ON raw.raw_nflverse_player_stats (game_id, player_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_player_stats_payload_gin_idx
    ON raw.raw_nflverse_player_stats USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_team_stats (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    week INTEGER,
    game_id TEXT,
    team TEXT,
    opponent TEXT,
    home_away TEXT,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_team_stats_batch_idx
    ON raw.raw_nflverse_team_stats (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_team_stats_season_week_idx
    ON raw.raw_nflverse_team_stats (season, week);
CREATE INDEX IF NOT EXISTS raw_nflverse_team_stats_game_team_idx
    ON raw.raw_nflverse_team_stats (game_id, team);
CREATE INDEX IF NOT EXISTS raw_nflverse_team_stats_payload_gin_idx
    ON raw.raw_nflverse_team_stats USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_injuries (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    week INTEGER,
    team TEXT,
    player_id TEXT,
    player_name TEXT,
    report_status TEXT,
    game_status TEXT,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_injuries_batch_idx
    ON raw.raw_nflverse_injuries (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_injuries_season_week_team_idx
    ON raw.raw_nflverse_injuries (season, week, team);
CREATE INDEX IF NOT EXISTS raw_nflverse_injuries_player_idx
    ON raw.raw_nflverse_injuries (player_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_injuries_payload_gin_idx
    ON raw.raw_nflverse_injuries USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_depth_charts (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    week INTEGER,
    team TEXT,
    player_id TEXT,
    player_name TEXT,
    position TEXT,
    depth_rank INTEGER,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_depth_charts_batch_idx
    ON raw.raw_nflverse_depth_charts (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_depth_charts_season_week_team_idx
    ON raw.raw_nflverse_depth_charts (season, week, team);
CREATE INDEX IF NOT EXISTS raw_nflverse_depth_charts_player_idx
    ON raw.raw_nflverse_depth_charts (player_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_depth_charts_payload_gin_idx
    ON raw.raw_nflverse_depth_charts USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_snap_counts (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    week INTEGER,
    game_id TEXT,
    team TEXT,
    player_id TEXT,
    player_name TEXT,
    offense_snaps INTEGER,
    defense_snaps INTEGER,
    special_snaps INTEGER,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_snap_counts_batch_idx
    ON raw.raw_nflverse_snap_counts (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_snap_counts_season_week_team_idx
    ON raw.raw_nflverse_snap_counts (season, week, team);
CREATE INDEX IF NOT EXISTS raw_nflverse_snap_counts_game_player_idx
    ON raw.raw_nflverse_snap_counts (game_id, player_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_snap_counts_payload_gin_idx
    ON raw.raw_nflverse_snap_counts USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_pbp_participation (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    game_id TEXT NOT NULL,
    play_id TEXT NOT NULL,
    player_id TEXT,
    player_name TEXT,
    team TEXT,
    role TEXT,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_participation_batch_idx
    ON raw.raw_nflverse_pbp_participation (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_participation_game_play_idx
    ON raw.raw_nflverse_pbp_participation (game_id, play_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_participation_player_idx
    ON raw.raw_nflverse_pbp_participation (player_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_pbp_participation_payload_gin_idx
    ON raw.raw_nflverse_pbp_participation USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_draft_picks (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    round INTEGER,
    pick_in_round INTEGER,
    overall_pick INTEGER,
    team TEXT,
    player_id TEXT,
    player_name TEXT,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_draft_picks_batch_idx
    ON raw.raw_nflverse_draft_picks (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_draft_picks_season_round_pick_idx
    ON raw.raw_nflverse_draft_picks (season, round, overall_pick);
CREATE INDEX IF NOT EXISTS raw_nflverse_draft_picks_player_idx
    ON raw.raw_nflverse_draft_picks (player_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_draft_picks_payload_gin_idx
    ON raw.raw_nflverse_draft_picks USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_trades (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    week INTEGER,
    transaction_id TEXT,
    team TEXT,
    player_id TEXT,
    player_name TEXT,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_trades_batch_idx
    ON raw.raw_nflverse_trades (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_trades_season_week_idx
    ON raw.raw_nflverse_trades (season, week);
CREATE INDEX IF NOT EXISTS raw_nflverse_trades_transaction_idx
    ON raw.raw_nflverse_trades (transaction_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_trades_payload_gin_idx
    ON raw.raw_nflverse_trades USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_standings (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    season INTEGER,
    week INTEGER,
    team TEXT,
    conference TEXT,
    division TEXT,
    wins INTEGER,
    losses INTEGER,
    ties INTEGER,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_standings_batch_idx
    ON raw.raw_nflverse_standings (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_standings_season_week_team_idx
    ON raw.raw_nflverse_standings (season, week, team);
CREATE INDEX IF NOT EXISTS raw_nflverse_standings_payload_gin_idx
    ON raw.raw_nflverse_standings USING GIN (payload);

CREATE TABLE IF NOT EXISTS raw.raw_espn_summary (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    espn_event_id TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type INTEGER,
    game_date TIMESTAMPTZ,
    summary_payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_espn_summary_batch_idx
    ON raw.raw_espn_summary (batch_id);
CREATE INDEX IF NOT EXISTS raw_espn_summary_event_ingested_idx
    ON raw.raw_espn_summary (espn_event_id, ingested_at DESC);
CREATE INDEX IF NOT EXISTS raw_espn_summary_payload_gin_idx
    ON raw.raw_espn_summary USING GIN (summary_payload);

CREATE TABLE IF NOT EXISTS raw.raw_espn_probabilities (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    espn_event_id TEXT NOT NULL,
    play_id TEXT,
    sequence INTEGER,
    seconds_left INTEGER,
    home_win_pct DOUBLE PRECISION,
    away_win_pct DOUBLE PRECISION,
    tie_pct DOUBLE PRECISION,
    probability_payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_espn_probabilities_batch_idx
    ON raw.raw_espn_probabilities (batch_id);
CREATE INDEX IF NOT EXISTS raw_espn_probabilities_event_seq_idx
    ON raw.raw_espn_probabilities (espn_event_id, sequence);
CREATE INDEX IF NOT EXISTS raw_espn_probabilities_event_play_idx
    ON raw.raw_espn_probabilities (espn_event_id, play_id);
CREATE INDEX IF NOT EXISTS raw_espn_probabilities_payload_gin_idx
    ON raw.raw_espn_probabilities USING GIN (probability_payload);
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS raw.raw_espn_probabilities;
DROP TABLE IF EXISTS raw.raw_espn_summary;
DROP TABLE IF EXISTS raw.raw_nflverse_standings;
DROP TABLE IF EXISTS raw.raw_nflverse_trades;
DROP TABLE IF EXISTS raw.raw_nflverse_draft_picks;
DROP TABLE IF EXISTS raw.raw_nflverse_pbp_participation;
DROP TABLE IF EXISTS raw.raw_nflverse_snap_counts;
DROP TABLE IF EXISTS raw.raw_nflverse_depth_charts;
DROP TABLE IF EXISTS raw.raw_nflverse_injuries;
DROP TABLE IF EXISTS raw.raw_nflverse_team_stats;
DROP TABLE IF EXISTS raw.raw_nflverse_player_stats;
DROP TABLE IF EXISTS raw.raw_nflverse_pbp;
DROP TABLE IF EXISTS raw.raw_ingest_batch;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0004_playerffranking_playernextgenstats"),
    ]

    operations = [
        migrations.RunSQL(FORWARDS_SQL, REVERSE_SQL),
    ]
