# Generated by Django 5.2.11 on 2026-02-24

from django.db import migrations

FORWARDS_SQL = """
CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw.raw_nflverse_draft_values (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT REFERENCES raw.raw_ingest_batch(id) ON DELETE SET NULL,
    pick INTEGER,
    stuart DOUBLE PRECISION,
    johnson DOUBLE PRECISION,
    hill DOUBLE PRECISION,
    otc DOUBLE PRECISION,
    pff DOUBLE PRECISION,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS raw_nflverse_draft_values_batch_idx
    ON raw.raw_nflverse_draft_values (batch_id);
CREATE INDEX IF NOT EXISTS raw_nflverse_draft_values_pick_idx
    ON raw.raw_nflverse_draft_values (pick);
CREATE INDEX IF NOT EXISTS raw_nflverse_draft_values_payload_gin_idx
    ON raw.raw_nflverse_draft_values USING GIN (payload);
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS raw.raw_nflverse_draft_values;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0005_raw_schema_tables"),
    ]

    operations = [
        migrations.RunSQL(FORWARDS_SQL, REVERSE_SQL),
    ]
