# Generated by Django 5.2.5 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0006_raw_draft_values_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="away_rest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="away_spread_odds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_rest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_spread_odds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="overtime",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="over_odds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="referee",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="game",
            name="under_odds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
