# Generated by Django 5.2.5 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0007_game_schedule_context_and_odds_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="away_timeouts_remaining",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="away_wp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="cp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="cpoe",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="drive_end_transition",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="play",
            name="drive_start_transition",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="play",
            name="drive_yards_penalized",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="ep",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="extra_point_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="fg_prob",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="fumble_recovery_1_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="fumble_recovery_1_team",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="play",
            name="fumble_recovery_1_yards",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="home_timeouts_remaining",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="home_wp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="interception_player_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="play",
            name="interception_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="kickoff_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="kickoff_fair_catch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="kickoff_in_endzone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="kickoff_returner_player_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="play",
            name="kickoff_returner_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="no_score_prob",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="out_of_bounds",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="pass_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="pass_defense_1_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="penalty_player_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="play",
            name="penalty_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="penalty_team",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="play",
            name="punt_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="punt_fair_catch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="punt_inside_twenty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="punt_returner_player_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="play",
            name="punt_returner_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="return_team",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="play",
            name="return_yards",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="rush_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="sack_player_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="play",
            name="sack_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="score_differential",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="series_result",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="play",
            name="special_teams_play",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="st_play_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="play",
            name="tackle_for_loss_1_player_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="play",
            name="td_prob",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="timeout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="timeout_team",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="play",
            name="touchback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="two_point_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="play",
            name="vegas_home_wp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="vegas_wp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
