# Generated by Django 5.2.5 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0008_play_extended_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="attendance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="div_game",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="spread_line",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="total_line",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
