# Generated by Django 5.2.5 on 2026-02-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0009_game_attendance_divgame_lines_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conference", models.CharField(blank=True, max_length=5)),
                ("division", models.CharField(blank=True, max_length=20)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("ties", models.IntegerField(default=0)),
                ("pct", models.FloatField(default=0.0)),
                ("div_rank", models.IntegerField(blank=True, null=True)),
                ("seed", models.IntegerField(blank=True, null=True)),
                ("points_for", models.IntegerField(blank=True, null=True)),
                ("points_against", models.IntegerField(blank=True, null=True)),
                ("point_diff", models.IntegerField(default=0)),
                ("sov", models.FloatField(blank=True, null=True)),
                ("sos", models.FloatField(blank=True, null=True)),
                ("streak", models.CharField(blank=True, max_length=12)),
                ("last_5", models.CharField(blank=True, max_length=12)),
                ("playoff_clincher", models.CharField(blank=True, max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_standings",
                        to="gridstream.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_standings",
                        to="gridstream.team",
                    ),
                ),
            ],
            options={
                "ordering": ["season_id", "conference", "division", "div_rank", "-pct"],
            },
        ),
        migrations.AddIndex(
            model_name="teamstanding",
            index=models.Index(
                fields=["season", "conference", "division"],
                name="gridstream_t_season__1ec2cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teamstanding",
            index=models.Index(
                fields=["season", "seed"], name="gridstream_t_season__147e3f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamstanding",
            unique_together={("season", "team")},
        ),
    ]
