# Generated by Django 5.2.5 on 2026-02-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gridstream", "0010_teamstanding_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameOfficial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=80)),
                ("position", models.CharField(blank=True, max_length=50)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officials",
                        to="gridstream.game",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "sequence", "name"],
                "unique_together": {("game", "name", "position")},
            },
        ),
        migrations.CreateModel(
            name="PlayerInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(default=0)),
                ("player_name", models.CharField(blank=True, max_length=80)),
                (
                    "player_espn_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("status", models.CharField(blank=True, max_length=40)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("game_day_availability", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injuries",
                        to="gridstream.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="gridstream.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gridstream.team",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "team", "sequence", "player_name"],
            },
        ),
        migrations.CreateModel(
            name="WinProbabilityPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "espn_play_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("sequence", models.IntegerField()),
                ("seconds_left", models.IntegerField(blank=True, null=True)),
                ("home_win_pct", models.FloatField(blank=True, null=True)),
                ("away_win_pct", models.FloatField(blank=True, null=True)),
                ("tie_pct", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="espn_summary", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="win_probability",
                        to="gridstream.game",
                    ),
                ),
                (
                    "play",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="win_probability_points",
                        to="gridstream.play",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "sequence"],
                "unique_together": {("game", "sequence")},
            },
        ),
        migrations.AddIndex(
            model_name="gameofficial",
            index=models.Index(
                fields=["game", "position"], name="gridstream_g_game_id_c4f95e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerinjury",
            index=models.Index(
                fields=["game", "team"], name="gridstream_p_game_id_9a95a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerinjury",
            index=models.Index(
                fields=["game", "player_espn_id"],
                name="gridstream_p_game_id_a9cd58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="winprobabilityplay",
            index=models.Index(
                fields=["game", "play"], name="gridstream_w_game_id_9cd45d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winprobabilityplay",
            index=models.Index(
                fields=["game", "espn_play_id"],
                name="gridstream_w_game_id_4de1d0_idx",
            ),
        ),
    ]
