# Generated by Django 5.2.11 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0011_gameofficial_playerinjury_winprobabilityplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="total_away_epa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="play",
            name="total_home_epa",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
