# Generated by Django 5.2.11 on 2026-03-01 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0014_players_directory_perf_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField(db_index=True)),
                ("espn_award_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-season", "name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="player",
            name="gridstream_pla_scope_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="gridstream__season__06a186_idx",
            old_name="gridstream_gam_season__4a19fe_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="gridstream__status_2c071d_idx",
            old_name="gridstream_gam_status_b47c66_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="gridstream__game_da_760007_idx",
            old_name="gridstream_gam_game_da_ab1e54_idx",
        ),
        migrations.RenameIndex(
            model_name="gameofficial",
            new_name="gridstream__game_id_f98421_idx",
            old_name="gridstream_g_game_id_c4f95e_idx",
        ),
        migrations.RenameIndex(
            model_name="play",
            new_name="gridstream__game_id_105e46_idx",
            old_name="gridstream_pla_game_id_fc66cf_idx",
        ),
        migrations.RenameIndex(
            model_name="play",
            new_name="gridstream__game_id_380875_idx",
            old_name="gridstream_pla_game_id_6ae344_idx",
        ),
        migrations.RenameIndex(
            model_name="play",
            new_name="gridstream__possess_fdf82e_idx",
            old_name="gridstream_pla_possess_f180e4_idx",
        ),
        migrations.RenameIndex(
            model_name="player",
            new_name="gridstream__current_37ecfc_idx",
            old_name="gridstream_pla_current_f361e1_idx",
        ),
        migrations.RenameIndex(
            model_name="player",
            new_name="gridstream__draft_y_ad326a_idx",
            old_name="gridstream_pla_draft_y_db931d_idx",
        ),
        migrations.RenameIndex(
            model_name="playercontract",
            new_name="gridstream__player__a13afc_idx",
            old_name="gridstream_pla_player__394ead_idx",
        ),
        migrations.RenameIndex(
            model_name="playerffranking",
            new_name="gridstream__season_151844_idx",
            old_name="gridstream_playerffranking_season_week_pos_idx",
        ),
        migrations.RenameIndex(
            model_name="playerffranking",
            new_name="gridstream__player__963b9d_idx",
            old_name="gridstream_playerffranking_player_season_idx",
        ),
        migrations.RenameIndex(
            model_name="playergamestats",
            new_name="gridstream__game_id_73510a_idx",
            old_name="gridstream_pla_game_id_ff111c_idx",
        ),
        migrations.RenameIndex(
            model_name="playergamestats",
            new_name="gridstream__player__afe895_idx",
            old_name="gridstream_pla_player__1139e9_idx",
        ),
        migrations.RenameIndex(
            model_name="playergamestats",
            new_name="gridstream__season__8da79f_idx",
            old_name="gridstream_pla_season__6365c0_idx",
        ),
        migrations.RenameIndex(
            model_name="playerinjury",
            new_name="gridstream__game_id_07e965_idx",
            old_name="gridstream_p_game_id_9a95a2_idx",
        ),
        migrations.RenameIndex(
            model_name="playerinjury",
            new_name="gridstream__game_id_c4990a_idx",
            old_name="gridstream_p_game_id_a9cd58_idx",
        ),
        migrations.RenameIndex(
            model_name="playernextgenstats",
            new_name="gridstream__player__49de72_idx",
            old_name="gridstream_playerngs_player_season_type_idx",
        ),
        migrations.RenameIndex(
            model_name="playernextgenstats",
            new_name="gridstream__season_d1f468_idx",
            old_name="gridstream_playerngs_season_week_type_idx",
        ),
        migrations.RenameIndex(
            model_name="playertransaction",
            new_name="gridstream__player__181ce4_idx",
            old_name="gridstream_pla_player__ebaf4f_idx",
        ),
        migrations.RenameIndex(
            model_name="playertransaction",
            new_name="gridstream__date_78021f_idx",
            old_name="gridstream_pla_date_1ddf3c_idx",
        ),
        migrations.RenameIndex(
            model_name="playertransaction",
            new_name="gridstream__to_team_3abbfc_idx",
            old_name="gridstream_pla_to_team_68e9a2_idx",
        ),
        migrations.RenameIndex(
            model_name="socialaccount",
            new_name="gridstream__team_id_7f9679_idx",
            old_name="gridstream_soc_team_id_573bcb_idx",
        ),
        migrations.RenameIndex(
            model_name="socialaccount",
            new_name="gridstream__player__4a9065_idx",
            old_name="gridstream_soc_player__ad0d5c_idx",
        ),
        migrations.RenameIndex(
            model_name="teamgamestats",
            new_name="gridstream__team_id_507981_idx",
            old_name="gridstream_tea_team_id_9ac3c3_idx",
        ),
        migrations.RenameIndex(
            model_name="teamstanding",
            new_name="gridstream__season__12f3ce_idx",
            old_name="gridstream_t_season__1ec2cf_idx",
        ),
        migrations.RenameIndex(
            model_name="teamstanding",
            new_name="gridstream__season__6228b2_idx",
            old_name="gridstream_t_season__147e3f_idx",
        ),
        migrations.RenameIndex(
            model_name="winprobabilityplay",
            new_name="gridstream__game_id_37e1cf_idx",
            old_name="gridstream_w_game_id_9cd45d_idx",
        ),
        migrations.RenameIndex(
            model_name="winprobabilityplay",
            new_name="gridstream__game_id_efc67e_idx",
            old_name="gridstream_w_game_id_4de1d0_idx",
        ),
        migrations.AlterField(
            model_name="player",
            name="roster_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACT", "Active"),
                    ("DEV", "Developmental"),
                    ("RES", "Reserve/Injured"),
                    ("RSR", "Reserve"),
                    ("RSN", "Reserve/Future"),
                    ("INA", "Inactive"),
                    ("NWT", "Not With Team"),
                    ("PUP", "PUP"),
                    ("SUS", "Suspended"),
                    ("NFI", "Non-Football Injury"),
                    ("EXE", "Exempt"),
                    ("TRD", "Traded"),
                    ("TRC", "Trade Complete"),
                    ("UFA", "Unrestricted Free Agent"),
                    ("RFA", "Restricted Free Agent"),
                    ("RET", "Retired"),
                    ("CUT", "Released"),
                    ("PRA", "Practice Squad"),
                ],
                help_text="Current roster status from nflverse",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="playerffranking",
            name="position",
            field=models.CharField(
                help_text="Position at time of ranking", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="playerffranking",
            name="position_rank",
            field=models.IntegerField(
                blank=True, help_text="Rank within position group (WR8 = 8)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerffranking",
            name="rank",
            field=models.FloatField(help_text="Expert Consensus Rank (lower = better)"),
        ),
        migrations.AlterField(
            model_name="playerffranking",
            name="rank_best",
            field=models.IntegerField(
                blank=True, help_text="Most optimistic rank", null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerffranking",
            name="rank_sd",
            field=models.FloatField(
                blank=True,
                help_text="Standard deviation — disagreement between experts",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerffranking",
            name="rank_worst",
            field=models.IntegerField(
                blank=True, help_text="Most pessimistic rank", null=True
            ),
        ),
        migrations.AlterField(
            model_name="playernextgenstats",
            name="metrics",
            field=models.JSONField(
                default=dict,
                help_text="Stat-type-specific NGS metrics (see class docstring)",
            ),
        ),
        migrations.AlterField(
            model_name="playernextgenstats",
            name="week",
            field=models.IntegerField(
                default=0, help_text="0 = season total; 1+ = game week"
            ),
        ),
        migrations.AddField(
            model_name="playeraward",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="gridstream.player",
            ),
        ),
        migrations.AddIndex(
            model_name="playeraward",
            index=models.Index(
                fields=["player", "season"], name="gridstream__player__e18c11_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playeraward",
            unique_together={("player", "season", "espn_award_id")},
        ),
    ]
