# Generated by Django 5.2.11 on 2026-03-02 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0016_player_career_stats_materialized"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerMaddenRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "madden_year",
                    models.SmallIntegerField(
                        help_text="Madden game title number (e.g., 24 for Madden NFL 24)"
                    ),
                ),
                (
                    "position_snapshot",
                    models.CharField(
                        help_text="Position as listed in Madden roster file",
                        max_length=5,
                    ),
                ),
                (
                    "team_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Team name as listed in Madden roster file",
                        max_length=40,
                    ),
                ),
                ("overall", models.SmallIntegerField(help_text="Overall rating (OVR)")),
                ("speed", models.SmallIntegerField(blank=True, null=True)),
                ("strength", models.SmallIntegerField(blank=True, null=True)),
                ("awareness", models.SmallIntegerField(blank=True, null=True)),
                ("agility", models.SmallIntegerField(blank=True, null=True)),
                ("acceleration", models.SmallIntegerField(blank=True, null=True)),
                (
                    "tackle",
                    models.SmallIntegerField(
                        blank=True, help_text="Tackle (DEF)", null=True
                    ),
                ),
                (
                    "power_moves",
                    models.SmallIntegerField(
                        blank=True, help_text="Power Moves (DL)", null=True
                    ),
                ),
                (
                    "finesse_moves",
                    models.SmallIntegerField(
                        blank=True, help_text="Finesse Moves (DL)", null=True
                    ),
                ),
                (
                    "throw_power",
                    models.SmallIntegerField(
                        blank=True, help_text="Throw Power (QB)", null=True
                    ),
                ),
                (
                    "catching",
                    models.SmallIntegerField(
                        blank=True, help_text="Catching (WR/TE/RB)", null=True
                    ),
                ),
                (
                    "route_running",
                    models.SmallIntegerField(
                        blank=True, help_text="Short Route Running (WR/TE)", null=True
                    ),
                ),
                (
                    "run_block",
                    models.SmallIntegerField(
                        blank=True, help_text="Run Block (OL)", null=True
                    ),
                ),
                (
                    "pass_block",
                    models.SmallIntegerField(
                        blank=True, help_text="Pass Block (OL)", null=True
                    ),
                ),
                (
                    "hit_power",
                    models.SmallIntegerField(
                        blank=True, help_text="Hit Power (DB/LB)", null=True
                    ),
                ),
                (
                    "man_coverage",
                    models.SmallIntegerField(
                        blank=True, help_text="Man Coverage (DB)", null=True
                    ),
                ),
                (
                    "zone_coverage",
                    models.SmallIntegerField(
                        blank=True, help_text="Zone Coverage (DB)", null=True
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="madden_ratings",
                        to="gridstream.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-madden_year"],
                "indexes": [
                    models.Index(
                        fields=["madden_year", "overall"],
                        name="gridstream__madden__dd5fd4_idx",
                    ),
                    models.Index(
                        fields=["player"], name="gridstream__player__ad6e26_idx"
                    ),
                ],
                "unique_together": {("player", "madden_year")},
            },
        ),
    ]
