# Generated by Django 5.2.11 on 2026-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0017_player_madden_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermaddenrating",
            name="ball_carrier_rating",
            field=models.SmallIntegerField(
                blank=True, help_text="Ball-carrying category score", null=True
            ),
        ),
        migrations.AddField(
            model_name="playermaddenrating",
            name="blocking_rating",
            field=models.SmallIntegerField(
                blank=True, help_text="Blocking category score", null=True
            ),
        ),
        migrations.AddField(
            model_name="playermaddenrating",
            name="defense_rating",
            field=models.SmallIntegerField(
                blank=True, help_text="Defense category score", null=True
            ),
        ),
        migrations.AddField(
            model_name="playermaddenrating",
            name="general_rating",
            field=models.SmallIntegerField(
                blank=True, help_text="General category score", null=True
            ),
        ),
        migrations.AddField(
            model_name="playermaddenrating",
            name="kicking_rating",
            field=models.SmallIntegerField(
                blank=True, help_text="Kicking category score", null=True
            ),
        ),
        migrations.AddField(
            model_name="playermaddenrating",
            name="passing_rating",
            field=models.SmallIntegerField(
                blank=True, help_text="Passing category score", null=True
            ),
        ),
        migrations.AddField(
            model_name="playermaddenrating",
            name="receiving_rating",
            field=models.SmallIntegerField(
                blank=True, help_text="Receiving category score", null=True
            ),
        ),
    ]
