# Generated by Django 5.2.11 on 2026-03-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0018_madden_category_scores"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamDvoaRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("REG", "Regular Season"),
                            ("POST", "Postseason"),
                        ],
                        default="REG",
                        max_length=4,
                    ),
                ),
                (
                    "week",
                    models.IntegerField(
                        default=0,
                        help_text="Source week number tied to this DVOA snapshot",
                    ),
                ),
                (
                    "record_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Source win-loss string (e.g. 14-3)",
                        max_length=20,
                    ),
                ),
                ("total_dvoa", models.FloatField(blank=True, null=True)),
                ("offense_dvoa", models.FloatField(blank=True, null=True)),
                ("defense_dvoa", models.FloatField(blank=True, null=True)),
                (
                    "special_teams_dvoa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "weighted_total_dvoa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "total_dvoa_rank",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "offense_dvoa_rank",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "defense_dvoa_rank",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "special_teams_dvoa_rank",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "weighted_total_dvoa_rank",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("last_week_rank", models.SmallIntegerField(blank=True, null=True)),
                (
                    "last_week_weighted_rank",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "non_adjusted_total_voi",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "offense_voa_unadjusted",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "defense_voa_unadjusted",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "special_teams_voa_unadjusted",
                    models.FloatField(blank=True, null=True),
                ),
                ("estimated_wins", models.FloatField(blank=True, null=True)),
                (
                    "past_schedule_dvoa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "future_schedule_dvoa",
                    models.FloatField(blank=True, null=True),
                ),
                ("variance", models.FloatField(blank=True, null=True)),
                (
                    "weighted_offense_dvoa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "weighted_defense_dvoa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "weighted_special_teams_dvoa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "metrics_raw",
                    models.JSONField(
                        default=dict,
                        help_text="Full source payload row from FTN DVOA API",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dvoa_ratings",
                        to="gridstream.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "season_type", "total_dvoa_rank"],
                "indexes": [
                    models.Index(
                        fields=["season", "season_type", "total_dvoa_rank"],
                        name="gridstream_tdvoa_ssr_idx",
                    ),
                    models.Index(
                        fields=["team", "season", "season_type"],
                        name="gridstream_tdvoa_tss_idx",
                    ),
                ],
                "unique_together": {("team", "season", "season_type", "week")},
            },
        ),
    ]
