# Generated by Django 5.2.11 on 2026-03-05 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0019_team_dvoa_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerRbsdmQbMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("week", models.IntegerField()),
                ("player_name", models.CharField(max_length=80)),
                ("player_key", models.CharField(db_index=True, max_length=80)),
                ("adj_epa_play", models.FloatField(blank=True, null=True)),
                ("epa_play", models.FloatField(blank=True, null=True)),
                ("epa_cpoe_composite", models.FloatField(blank=True, null=True)),
                ("cpoe", models.FloatField(blank=True, null=True)),
                ("success_rate", models.FloatField(blank=True, null=True)),
                ("air_yards", models.FloatField(blank=True, null=True)),
                ("expected_cmppct", models.FloatField(blank=True, null=True)),
                ("cmppct", models.FloatField(blank=True, null=True)),
                ("plays", models.IntegerField(blank=True, null=True)),
                ("table_context", models.CharField(blank=True, max_length=255)),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="RBSDM QB row metrics payload"
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rbsdm_qb_metrics",
                        to="gridstream.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="gridstream.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "-week", "player_name"],
                "indexes": [
                    models.Index(
                        fields=["season", "week"], name="gridstream__season_1900c2_idx"
                    ),
                    models.Index(
                        fields=["player", "season"],
                        name="gridstream__player__b98eda_idx",
                    ),
                    models.Index(
                        fields=["player_key", "season"],
                        name="gridstream__player__7928fe_idx",
                    ),
                ],
                "unique_together": {("team", "season", "week", "player_key")},
            },
        ),
        migrations.CreateModel(
            name="TeamRbsdmMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                (
                    "week",
                    models.IntegerField(
                        default=0,
                        help_text="Week number, or 0 for season-level datasets",
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("stats_offense_weekly", "RBSDM Stats Offense (Weekly)"),
                            ("stats_defense_weekly", "RBSDM Stats Defense (Weekly)"),
                            ("luck_offense_weekly", "RBSDM Luck Offense (Weekly)"),
                            ("luck_defense_weekly", "RBSDM Luck Defense (Weekly)"),
                            (
                                "passfreq_neutral_yearly",
                                "RBSDM Neutral Pass Frequency (Season)",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("table_context", models.CharField(blank=True, max_length=255)),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="RBSDM row metrics payload"
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rbsdm_metrics",
                        to="gridstream.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "dataset", "week", "team__abbreviation"],
                "indexes": [
                    models.Index(
                        fields=["season", "dataset", "week"],
                        name="gridstream__season_5b0c46_idx",
                    ),
                    models.Index(
                        fields=["team", "season", "dataset"],
                        name="gridstream__team_id_69bb54_idx",
                    ),
                ],
                "unique_together": {("team", "season", "week", "dataset")},
            },
        ),
    ]
