# Generated by Django 5.2.11 on 2026-03-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0020_playerrbsdmqbmetric_teamrbsdmmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="depth_chart_rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="depth_chart_status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
