# Generated by Django 5.2.11 on 2026-03-08 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0022_teamfreeagenttrackerentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftProspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.IntegerField(help_text="Draft year / class year, e.g. 2026"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("nfldraftbuzz", "NFLDraftBuzz")],
                        default="nfldraftbuzz",
                        max_length=30,
                    ),
                ),
                ("source_slug", models.SlugField(max_length=160)),
                ("source_url", models.URLField(max_length=500)),
                ("name", models.CharField(max_length=120)),
                ("position", models.CharField(blank=True, max_length=20)),
                ("school", models.CharField(blank=True, max_length=120)),
                ("class_year", models.CharField(blank=True, max_length=40)),
                ("hometown", models.CharField(blank=True, max_length=120)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("jersey_number", models.CharField(blank=True, max_length=10)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("college_logo_url", models.URLField(blank=True, max_length=500)),
                ("overall_rating", models.FloatField(blank=True, null=True)),
                ("overall_rank", models.IntegerField(blank=True, null=True)),
                ("position_rank", models.IntegerField(blank=True, null=True)),
                ("position_rank_group", models.CharField(blank=True, max_length=20)),
                ("draft_projection", models.CharField(blank=True, max_length=80)),
                ("all_scouts_overall_rank", models.FloatField(blank=True, null=True)),
                ("all_scouts_position_rank", models.FloatField(blank=True, null=True)),
                ("height", models.CharField(blank=True, max_length=16)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("forty_yard", models.FloatField(blank=True, null=True)),
                ("hand_size", models.CharField(blank=True, max_length=20)),
                ("arm_length", models.CharField(blank=True, max_length=20)),
                ("age", models.FloatField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("college_games", models.IntegerField(blank=True, null=True)),
                ("college_snaps", models.IntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "strengths",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "weaknesses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "honors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "production_stats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top on-page production stats, e.g. tackles / sacks / INT",
                    ),
                ),
                (
                    "scouting_grades",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="NFLDraftBuzz grading/rating rows, e.g. tackling / coverage / ESPN",
                    ),
                ),
                (
                    "measurable_percentiles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Percentile values for height/weight/forty/hand/arm on the page",
                    ),
                ),
                (
                    "recruiting_ratings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Third-party recruiting/grade badges like ESPN / 247 / Rivals",
                    ),
                ),
                (
                    "comparison_players",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Comparable players and similarity percentages",
                    ),
                ),
                ("source_last_updated", models.DateField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["season", "overall_rank", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="teamfreeagenttrackerentry",
            new_name="gridstream__team_id_aaf42e_idx",
            old_name="gridstream__team_id_9295e5_idx",
        ),
        migrations.RenameIndex(
            model_name="teamfreeagenttrackerentry",
            new_name="gridstream__signed__bad260_idx",
            old_name="gridstream__signed__cb1fcf_idx",
        ),
        migrations.RenameIndex(
            model_name="teamfreeagenttrackerentry",
            new_name="gridstream__player__83515f_idx",
            old_name="gridstream__player__d77e64_idx",
        ),
        migrations.RenameIndex(
            model_name="teamfreeagenttrackerentry",
            new_name="gridstream__season_59ff9b_idx",
            old_name="gridstream__season__17a24d_idx",
        ),
        migrations.AddIndex(
            model_name="draftprospect",
            index=models.Index(
                fields=["season", "source"], name="gridstream__season_cbaf0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftprospect",
            index=models.Index(
                fields=["season", "overall_rank"], name="gridstream__season_495780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftprospect",
            index=models.Index(
                fields=["season", "position"], name="gridstream__season_98298d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftprospect",
            index=models.Index(
                fields=["season", "school"], name="gridstream__season_839ca5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="draftprospect",
            unique_together={("season", "source", "source_slug")},
        ),
    ]
