# Generated by Django 5.2.11 on 2026-03-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0023_draftprospect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertransaction",
            name="contract_apy",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playertransaction",
            name="contract_guaranteed",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playertransaction",
            name="contract_total_value",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playertransaction",
            name="contract_years",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
