# Generated by Django 5.2.11 on 2026-03-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0026_draftmockdraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftprospect",
            name="source",
            field=models.CharField(
                choices=[
                    ("nfldraftbuzz", "NFLDraftBuzz"),
                    ("nflmockdraftdb", "NFLMockDraftDatabase"),
                ],
                default="nfldraftbuzz",
                max_length=30,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="DraftMockDraft",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("season", models.IntegerField()),
                        ("slug", models.SlugField(max_length=160)),
                        ("source_key", models.CharField(max_length=80)),
                        ("source_label", models.CharField(max_length=160)),
                        (
                            "source_analyst",
                            models.CharField(blank=True, default="", max_length=80),
                        ),
                        (
                            "source_outlet",
                            models.CharField(blank=True, default="", max_length=80),
                        ),
                        (
                            "source_url",
                            models.URLField(blank=True, default="", max_length=500),
                        ),
                        ("source_updated", models.DateField(blank=True, null=True)),
                        ("picks", models.JSONField(default=list)),
                        ("scraped_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "ordering": ["season", "source_label"],
                        "indexes": [
                            models.Index(
                                fields=["season"], name="gridstream__season_3b39dc_idx"
                            ),
                            models.Index(
                                fields=["season", "source_key"],
                                name="gridstream__season_03737a_idx",
                            ),
                        ],
                        "unique_together": {("season", "slug")},
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRAS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ras_player_id",
                    models.IntegerField(
                        db_index=True, help_text="ras.football PlayerID", unique=True
                    ),
                ),
                (
                    "ras_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Composite RAS out of 10.00",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "ras_summary",
                    models.TextField(
                        blank=True, help_text="Full sentence from ras.football"
                    ),
                ),
                (
                    "has_ras",
                    models.BooleanField(
                        default=False,
                        help_text="False if player did not qualify for a score",
                    ),
                ),
                ("ras_name", models.CharField(blank=True, max_length=200)),
                ("position", models.CharField(blank=True, max_length=10)),
                ("draft_year", models.IntegerField(blank=True, null=True)),
                ("draft_round", models.IntegerField(blank=True, null=True)),
                ("draft_pick", models.IntegerField(blank=True, null=True)),
                ("is_undrafted", models.BooleanField(default=False)),
                (
                    "is_prospect",
                    models.BooleanField(
                        default=False,
                        help_text="True for pre-draft prospects (e.g. 2026 class)",
                    ),
                ),
                (
                    "ras_image_key",
                    models.CharField(
                        blank=True,
                        help_text="MinIO object key, e.g. '4883.png'",
                        max_length=500,
                    ),
                ),
                (
                    "ras_image_team",
                    models.CharField(
                        blank=True,
                        help_text="Team name used for overlay (blank = no overlay)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ras",
                        to="gridstream.player",
                    ),
                ),
            ],
            options={
                "ordering": ["ras_player_id"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="DraftProspectRanking",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("season", models.IntegerField()),
                        (
                            "source",
                            models.CharField(
                                choices=[
                                    (
                                        "nflmockdraftdb_consensus",
                                        "Consensus (NFLMockDraftDatabase)",
                                    ),
                                    (
                                        "nflmockdraftdb_daniel_jeremiah",
                                        "Daniel Jeremiah (NFL.com)",
                                    ),
                                    (
                                        "nflmockdraftdb_dane_brugler",
                                        "Dane Brugler (The Athletic)",
                                    ),
                                    (
                                        "nflmockdraftdb_the_draft_network",
                                        "The Draft Network",
                                    ),
                                    (
                                        "nflmockdraftdb_field_yates",
                                        "Field Yates (ESPN)",
                                    ),
                                    ("nflmockdraftdb_tankathon", "Tankathon"),
                                    (
                                        "nflmockdraftdb_bleacher_report",
                                        "Bleacher Report",
                                    ),
                                    (
                                        "nflmockdraftdb_rob_rang",
                                        "Rob Rang (Fox Sports)",
                                    ),
                                    (
                                        "nflmockdraftdb_michael_renner",
                                        "Michael Renner (CBS Sports)",
                                    ),
                                    (
                                        "nflmockdraftdb_ryan_wilson",
                                        "Ryan Wilson (CBS Sports)",
                                    ),
                                    (
                                        "nflmockdraftdb_charles_mcdonald",
                                        "Charles McDonald (Yahoo Sports)",
                                    ),
                                ],
                                max_length=80,
                            ),
                        ),
                        ("source_label", models.CharField(max_length=120)),
                        ("source_analyst", models.CharField(blank=True, max_length=80)),
                        ("source_outlet", models.CharField(blank=True, max_length=80)),
                        ("source_url", models.URLField(blank=True, max_length=500)),
                        ("source_updated", models.DateField(blank=True, null=True)),
                        ("rank", models.IntegerField()),
                        ("name", models.CharField(max_length=120)),
                        ("name_slug", models.SlugField(max_length=160)),
                        ("position", models.CharField(blank=True, max_length=20)),
                        ("school", models.CharField(blank=True, max_length=120)),
                        ("scraped_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "prospect",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="external_rankings",
                                to="gridstream.draftprospect",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["season", "source", "rank"],
                        "indexes": [
                            models.Index(
                                fields=["season", "source"],
                                name="gridstream__season_c3c485_idx",
                            ),
                            models.Index(
                                fields=["season", "rank"],
                                name="gridstream__season_d04d8f_idx",
                            ),
                            models.Index(
                                fields=["name_slug", "season"],
                                name="gridstream__name_sl_e81182_idx",
                            ),
                        ],
                        "unique_together": {("season", "source", "name_slug")},
                    },
                ),
            ],
        ),
    ]
