# Generated by Django 5.2.12 on 2026-03-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gridstream", "0030_playertransaction_handled"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("espn", "ESPN"),
                            ("rotowire", "RotoWire"),
                            ("pfr", "Pro Football Rumors"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=250, unique=True),
                ),
                ("headline", models.CharField(max_length=600)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField(max_length=1000)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True, related_name="news_articles", to="gridstream.player"
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="news_articles", to="gridstream.team"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "published_at"],
                        name="gridstream__source_f3678a_idx",
                    )
                ],
            },
        ),
    ]
