"""
Import RBSDM CSV exports into Gridstream analytics tables.

Expected files (generated by scripts/rbsdm/extract-rbsdm.mjs):
  - stats_offense_weekly.csv
  - stats_defense_weekly.csv
  - luck_offense_weekly.csv
  - luck_defense_weekly.csv (optional)
  - passfreq_neutral_yearly.csv (optional)
  - stats_qb_weekly.csv
"""

import csv
import re
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils.dateparse import parse_datetime

from gridstream.models import (
    Team,
    Player,
    TeamRbsdmMetric,
    PlayerRbsdmQbMetric,
)

TEAM_ABBR_NORMALIZE = {"LAR": "LA", "STL": "LA", "SD": "LAC", "OAK": "LV"}
TEAM_DATASET_FILES = {
    "stats_offense_weekly": "stats_offense_weekly.csv",
    "stats_defense_weekly": "stats_defense_weekly.csv",
    "luck_offense_weekly": "luck_offense_weekly.csv",
    "luck_defense_weekly": "luck_defense_weekly.csv",
    "passfreq_neutral_yearly": "passfreq_neutral_yearly.csv",
}
QB_DATASET_FILE = "stats_qb_weekly.csv"
META_KEYS = {
    "dataset",
    "season_start",
    "season_end",
    "week_start",
    "week_end",
    "table_context",
    "captured_at",
    "row_order",
    "abbr",
    "team",
    "col_1",
}


def canonical_name_key(value):
    if not value:
        return ""
    return "".join(ch for ch in str(value).lower() if ch.isalnum())


def parse_team_abbr_from_logo_url(value):
    if not value:
        return None
    match = re.search(r"/([a-z0-9]{2,4})\.png(?:$|\?)", str(value).lower())
    if not match:
        return None
    return match.group(1).upper()


def coerce_value(value):
    if value is None:
        return None
    text = str(value).strip()
    if text == "":
        return None
    if text.endswith("%"):
        text = text[:-1].strip()
    if re.fullmatch(r"-?\d+", text):
        try:
            return int(text)
        except (TypeError, ValueError):
            return None
    if re.fullmatch(r"-?\d+\.\d+", text):
        try:
            return float(text)
        except (TypeError, ValueError):
            return None
    return str(value).strip()


def parse_int(value, default=None):
    val = coerce_value(value)
    if isinstance(val, int):
        return val
    if isinstance(val, float):
        return int(val)
    return default


def parse_float(value, default=None):
    val = coerce_value(value)
    if isinstance(val, (int, float)):
        return float(val)
    return default


class Command(BaseCommand):
    help = "Import RBSDM CSV exports into team/player metric tables."

    def add_arguments(self, parser):
        parser.add_argument(
            "--dir",
            dest="import_dir",
            required=True,
            help="Directory containing RBSDM export CSV files.",
        )
        parser.add_argument(
            "--replace",
            action="store_true",
            help="Delete existing RBSDM metric rows before importing.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse and report counts without writing to the DB.",
        )

    def handle(self, *args, **options):
        import_dir = Path(options["import_dir"]).expanduser().resolve()
        replace = bool(options["replace"])
        dry_run = bool(options["dry_run"])

        if not import_dir.exists() or not import_dir.is_dir():
            raise CommandError(f"Directory not found: {import_dir}")

        self.stdout.write(f"Import dir: {import_dir}")
        if dry_run:
            self.stdout.write(self.style.WARNING("Dry-run mode enabled."))

        teams = Team.objects.using("nfl").all()
        team_by_abbr = {
            TEAM_ABBR_NORMALIZE.get(t.abbreviation.upper(), t.abbreviation.upper()): t
            for t in teams
        }
        players = list(
            Player.objects.using("nfl").only(
                "id", "display_name", "short_name", "current_team_id"
            )
        )
        players_by_key = {}
        for player in players:
            for raw in (player.display_name, player.short_name):
                key = canonical_name_key(raw)
                if not key:
                    continue
                players_by_key.setdefault(key, []).append(player)

        counts = {
            "team_rows_processed": 0,
            "team_rows_upserted": 0,
            "qb_rows_processed": 0,
            "qb_rows_upserted": 0,
            "skipped_team_rows": 0,
            "skipped_qb_rows": 0,
        }

        with transaction.atomic(using="nfl"):
            if replace and not dry_run:
                TeamRbsdmMetric.objects.using("nfl").all().delete()
                PlayerRbsdmQbMetric.objects.using("nfl").all().delete()
                self.stdout.write(
                    self.style.WARNING("Deleted existing RBSDM metric rows.")
                )

            for dataset, filename in TEAM_DATASET_FILES.items():
                file_path = import_dir / filename
                if not file_path.exists():
                    self.stdout.write(self.style.WARNING(f"[skip] Missing {filename}"))
                    continue
                self._import_team_dataset(
                    dataset,
                    file_path,
                    team_by_abbr,
                    counts,
                    dry_run=dry_run,
                )

            qb_path = import_dir / QB_DATASET_FILE
            if qb_path.exists():
                self._import_qb_dataset(
                    qb_path,
                    team_by_abbr,
                    players_by_key,
                    counts,
                    dry_run=dry_run,
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f"[skip] Missing {QB_DATASET_FILE}")
                )

            if dry_run:
                transaction.set_rollback(True, using="nfl")

        self.stdout.write(self.style.SUCCESS("RBSDM import complete"))
        for key, value in counts.items():
            self.stdout.write(f"  {key}: {value}")

    def _import_team_dataset(
        self,
        dataset,
        file_path,
        team_by_abbr,
        counts,
        *,
        dry_run=False,
    ):
        self.stdout.write(f"Importing {dataset} from {file_path.name}...")
        with file_path.open("r", encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                counts["team_rows_processed"] += 1

                raw_abbr = (row.get("abbr") or "").strip().upper()
                normalized_abbr = TEAM_ABBR_NORMALIZE.get(raw_abbr, raw_abbr)
                team = team_by_abbr.get(normalized_abbr)
                if not team:
                    counts["skipped_team_rows"] += 1
                    continue

                season = parse_int(row.get("season_start"))
                if season is None:
                    counts["skipped_team_rows"] += 1
                    continue
                week = parse_int(row.get("week_start"), default=0)
                if dataset == "passfreq_neutral_yearly":
                    week = 0

                metrics = {}
                for key, raw_value in row.items():
                    if key in META_KEYS:
                        continue
                    parsed = coerce_value(raw_value)
                    if parsed is not None:
                        metrics[key] = parsed

                captured_at = parse_datetime((row.get("captured_at") or "").strip())
                table_context = (row.get("table_context") or "").strip()

                if dry_run:
                    counts["team_rows_upserted"] += 1
                    continue

                TeamRbsdmMetric.objects.using("nfl").update_or_create(
                    team=team,
                    season=season,
                    week=week,
                    dataset=dataset,
                    defaults={
                        "table_context": table_context,
                        "metrics": metrics,
                        "captured_at": captured_at,
                    },
                )
                counts["team_rows_upserted"] += 1

    def _import_qb_dataset(
        self,
        file_path,
        team_by_abbr,
        players_by_key,
        counts,
        *,
        dry_run=False,
    ):
        self.stdout.write(f"Importing QB weekly metrics from {file_path.name}...")
        with file_path.open("r", encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                counts["qb_rows_processed"] += 1
                season = parse_int(row.get("season_start"))
                week = parse_int(row.get("week_start"))
                player_name = (row.get("player") or "").strip()
                player_key = canonical_name_key(player_name)
                if season is None or week is None or not player_key:
                    counts["skipped_qb_rows"] += 1
                    continue

                team_abbr = parse_team_abbr_from_logo_url(row.get("team"))
                team = team_by_abbr.get(TEAM_ABBR_NORMALIZE.get(team_abbr, team_abbr))
                player = self._match_player(player_key, team, players_by_key)

                metrics = {}
                for key, raw_value in row.items():
                    if key in META_KEYS | {"player"}:
                        continue
                    parsed = coerce_value(raw_value)
                    if parsed is not None:
                        metrics[key] = parsed

                captured_at = parse_datetime((row.get("captured_at") or "").strip())
                table_context = (row.get("table_context") or "").strip()

                defaults = {
                    "player": player,
                    "player_name": player_name,
                    "adj_epa_play": parse_float(row.get("adj_epa_play")),
                    "epa_play": parse_float(row.get("epa_play")),
                    "epa_cpoe_composite": parse_float(row.get("epa_cpoe_composite")),
                    "cpoe": parse_float(row.get("cpoe")),
                    "success_rate": parse_float(row.get("success_rate")),
                    "air_yards": parse_float(row.get("air_yards")),
                    "expected_cmppct": parse_float(row.get("expected_cmppct")),
                    "cmppct": parse_float(row.get("cmppct")),
                    "plays": parse_int(row.get("plays")),
                    "table_context": table_context,
                    "metrics": metrics,
                    "captured_at": captured_at,
                }

                if dry_run:
                    counts["qb_rows_upserted"] += 1
                    continue

                PlayerRbsdmQbMetric.objects.using("nfl").update_or_create(
                    team=team,
                    season=season,
                    week=week,
                    player_key=player_key,
                    defaults=defaults,
                )
                counts["qb_rows_upserted"] += 1

    @staticmethod
    def _match_player(player_key, team, players_by_key):
        candidates = players_by_key.get(player_key, [])
        if not candidates:
            return None
        if len(candidates) == 1:
            return candidates[0]
        if team:
            team_matches = [p for p in candidates if p.current_team_id == team.id]
            if len(team_matches) == 1:
                return team_matches[0]
        return None
