# Generated by Django 5.2.11 on 2026-02-10 14:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "year",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current_week", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "espn_id",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                (
                    "abbreviation",
                    models.CharField(db_index=True, max_length=5, unique=True),
                ),
                ("slug", models.SlugField(unique=True)),
                ("location", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=80)),
                ("short_display_name", models.CharField(max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50)),
                ("color_primary", models.CharField(max_length=6)),
                ("color_secondary", models.CharField(blank=True, max_length=6)),
                ("conference", models.CharField(max_length=5)),
                ("division", models.CharField(max_length=15)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["conference", "division", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espn_id", models.CharField(blank=True, db_index=True, max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=60)),
                ("state", models.CharField(blank=True, max_length=30)),
                ("country", models.CharField(default="US", max_length=30)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "roof_type",
                    models.CharField(
                        choices=[
                            ("outdoors", "Outdoors"),
                            ("dome", "Dome"),
                            ("retractable", "Retractable"),
                        ],
                        default="outdoors",
                        max_length=15,
                    ),
                ),
                ("surface", models.CharField(blank=True, max_length=30)),
                ("is_indoor", models.BooleanField(default=False)),
                ("pfr_stadium_id", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "espn_event_id",
                    models.CharField(
                        db_index=True,
                        help_text="ESPN event ID, e.g. '401772988'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nflverse_game_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="nflverse game ID, e.g. '2025_22_SEA_NE'",
                        max_length=30,
                    ),
                ),
                ("pfr_game_id", models.CharField(blank=True, max_length=20)),
                ("week", models.IntegerField(db_index=True)),
                ("game_date", models.DateField()),
                ("game_time", models.TimeField(blank=True, null=True)),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("REG", "Regular Season"),
                            ("POST", "Postseason"),
                            ("PRE", "Preseason"),
                        ],
                        default="REG",
                        max_length=4,
                    ),
                ),
                ("is_division_game", models.BooleanField(default=False)),
                ("game_note", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("halftime", "Halftime"),
                            ("end_period", "End of Period"),
                            ("delayed", "Delayed"),
                            ("final", "Final"),
                            ("final_ot", "Final (OT)"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("quarter", models.IntegerField(blank=True, null=True)),
                ("clock", models.CharField(blank=True, max_length=10)),
                ("home_score", models.IntegerField(default=0)),
                ("away_score", models.IntegerField(default=0)),
                ("home_score_q1", models.IntegerField(default=0)),
                ("home_score_q2", models.IntegerField(default=0)),
                ("home_score_q3", models.IntegerField(default=0)),
                ("home_score_q4", models.IntegerField(default=0)),
                ("home_score_ot", models.IntegerField(default=0)),
                ("away_score_q1", models.IntegerField(default=0)),
                ("away_score_q2", models.IntegerField(default=0)),
                ("away_score_q3", models.IntegerField(default=0)),
                ("away_score_q4", models.IntegerField(default=0)),
                ("away_score_ot", models.IntegerField(default=0)),
                ("spread", models.FloatField(blank=True, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
                ("home_moneyline", models.IntegerField(blank=True, null=True)),
                ("away_moneyline", models.IntegerField(blank=True, null=True)),
                ("spread_open", models.FloatField(blank=True, null=True)),
                ("total_open", models.FloatField(blank=True, null=True)),
                ("odds_provider", models.CharField(blank=True, max_length=50)),
                ("weather_temp", models.IntegerField(blank=True, null=True)),
                ("weather_condition", models.CharField(blank=True, max_length=50)),
                ("weather_condition_id", models.IntegerField(blank=True, null=True)),
                ("weather_wind", models.CharField(blank=True, max_length=50)),
                ("weather_humidity", models.IntegerField(blank=True, null=True)),
                ("weather_detail", models.CharField(blank=True, max_length=200)),
                ("broadcast_network", models.CharField(blank=True, max_length=20)),
                (
                    "broadcast_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("broadcast_market", models.CharField(blank=True, max_length=20)),
                ("home_record", models.CharField(blank=True, max_length=15)),
                ("away_record", models.CharField(blank=True, max_length=15)),
                ("home_coach", models.CharField(blank=True, max_length=60)),
                ("away_coach", models.CharField(blank=True, max_length=60)),
                ("home_qb_name", models.CharField(blank=True, max_length=60)),
                ("away_qb_name", models.CharField(blank=True, max_length=60)),
                ("home_qb_espn_id", models.CharField(blank=True, max_length=20)),
                ("away_qb_espn_id", models.CharField(blank=True, max_length=20)),
                ("is_simulation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "simulation_source_game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="redzone.game",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="redzone.season",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="redzone.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="redzone.team",
                    ),
                ),
                (
                    "possession_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="redzone.team",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="redzone.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-game_date", "game_time"],
            },
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_number", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=200)),
                ("start_quarter", models.IntegerField(blank=True, null=True)),
                ("start_clock", models.CharField(blank=True, max_length=10)),
                ("start_yardline", models.IntegerField(blank=True, null=True)),
                ("end_quarter", models.IntegerField(blank=True, null=True)),
                ("end_clock", models.CharField(blank=True, max_length=10)),
                ("end_yardline", models.IntegerField(blank=True, null=True)),
                ("total_yards", models.IntegerField(default=0)),
                ("play_count", models.IntegerField(default=0)),
                ("first_downs", models.IntegerField(default=0)),
                ("time_elapsed", models.CharField(blank=True, max_length=10)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("touchdown", "Touchdown"),
                            ("field_goal", "Field Goal"),
                            ("punt", "Punt"),
                            ("turnover", "Turnover"),
                            ("turnover_on_downs", "Turnover on Downs"),
                            ("safety", "Safety"),
                            ("end_of_half", "End of Half"),
                            ("end_of_game", "End of Game"),
                            ("missed_fg", "Missed FG"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_score", models.BooleanField(default=False)),
                ("inside_20", models.BooleanField(default=False)),
                ("drive_epa", models.FloatField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drives",
                        to="redzone.game",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="redzone.team"
                    ),
                ),
            ],
            options={
                "ordering": ["game", "drive_number"],
            },
        ),
        migrations.CreateModel(
            name="GameLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("official_stream", "Official Stream"),
                            ("reddit_thread", "Reddit Game Thread"),
                            ("social_hashtag", "Social Media Hashtag"),
                            ("nflbite", "NFLBite Stream"),
                            ("highlight", "Highlight Reel"),
                            ("recap", "Recap Article"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500)),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="redzone.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espn_play_id", models.CharField(blank=True, max_length=20)),
                ("nflverse_play_id", models.FloatField(blank=True, null=True)),
                (
                    "sequence",
                    models.IntegerField(
                        help_text="Ordering within the game (0-indexed)"
                    ),
                ),
                ("quarter", models.IntegerField(blank=True, null=True)),
                ("clock", models.CharField(blank=True, max_length=10)),
                ("game_seconds_remaining", models.FloatField(blank=True, null=True)),
                ("half_seconds_remaining", models.FloatField(blank=True, null=True)),
                ("quarter_seconds_remaining", models.FloatField(blank=True, null=True)),
                ("down", models.IntegerField(blank=True, null=True)),
                ("distance", models.IntegerField(blank=True, null=True)),
                ("yard_line", models.IntegerField(blank=True, null=True)),
                ("side_of_field", models.CharField(blank=True, max_length=5)),
                ("down_distance_text", models.CharField(blank=True, max_length=30)),
                (
                    "play_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("run", "Run"),
                            ("punt", "Punt"),
                            ("kickoff", "Kickoff"),
                            ("field_goal", "Field Goal"),
                            ("extra_point", "Extra Point"),
                            ("two_point_attempt", "Two Point Attempt"),
                            ("qb_kneel", "QB Kneel"),
                            ("qb_spike", "QB Spike"),
                            ("no_play", "No Play (Penalty)"),
                            ("end_of_half", "End of Half"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=200)),
                ("yards_gained", models.FloatField(blank=True, null=True)),
                ("is_scoring_play", models.BooleanField(default=False)),
                ("home_score_after", models.IntegerField(default=0)),
                ("away_score_after", models.IntegerField(default=0)),
                ("end_down", models.IntegerField(blank=True, null=True)),
                ("end_distance", models.IntegerField(blank=True, null=True)),
                ("end_yard_line", models.IntegerField(blank=True, null=True)),
                ("touchdown", models.BooleanField(default=False)),
                ("interception", models.BooleanField(default=False)),
                ("fumble", models.BooleanField(default=False)),
                ("fumble_lost", models.BooleanField(default=False)),
                ("sack", models.BooleanField(default=False)),
                ("penalty", models.BooleanField(default=False)),
                ("penalty_type", models.CharField(blank=True, max_length=80)),
                ("penalty_yards", models.IntegerField(blank=True, null=True)),
                ("complete_pass", models.BooleanField(default=False)),
                ("first_down", models.BooleanField(default=False)),
                ("shotgun", models.BooleanField(blank=True, null=True)),
                ("no_huddle", models.BooleanField(blank=True, null=True)),
                ("qb_dropback", models.BooleanField(blank=True, null=True)),
                ("qb_scramble", models.BooleanField(blank=True, null=True)),
                ("air_yards", models.FloatField(blank=True, null=True)),
                ("yards_after_catch", models.FloatField(blank=True, null=True)),
                (
                    "pass_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left"),
                            ("middle", "Middle"),
                            ("right", "Right"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "run_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left"),
                            ("middle", "Middle"),
                            ("right", "Right"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "run_gap",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("guard", "Guard"),
                            ("tackle", "Tackle"),
                            ("end", "End"),
                        ],
                        max_length=6,
                    ),
                ),
                ("passer_player_name", models.CharField(blank=True, max_length=60)),
                ("passer_player_id", models.CharField(blank=True, max_length=20)),
                ("rusher_player_name", models.CharField(blank=True, max_length=60)),
                ("rusher_player_id", models.CharField(blank=True, max_length=20)),
                ("receiver_player_name", models.CharField(blank=True, max_length=60)),
                ("receiver_player_id", models.CharField(blank=True, max_length=20)),
                ("field_goal_result", models.CharField(blank=True, max_length=10)),
                ("kick_distance", models.FloatField(blank=True, null=True)),
                ("epa", models.FloatField(blank=True, null=True)),
                ("wpa", models.FloatField(blank=True, null=True)),
                ("success", models.FloatField(blank=True, null=True)),
                ("wall_clock", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plays",
                        to="redzone.drive",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="redzone.game",
                    ),
                ),
                (
                    "defensive_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="defensive_plays",
                        to="redzone.team",
                    ),
                ),
                (
                    "possession_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offensive_plays",
                        to="redzone.team",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_full_game",
                    models.BooleanField(
                        default=False,
                        help_text="True if this contains every play from the source game.",
                    ),
                ),
                ("play_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_game",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this playbook is a full game replay, the source game.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="redzone.game",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScoringPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quarter", models.IntegerField()),
                ("clock", models.CharField(blank=True, max_length=10)),
                (
                    "score_type",
                    models.CharField(
                        choices=[
                            ("TD", "Touchdown"),
                            ("FG", "Field Goal"),
                            ("PAT", "Extra Point"),
                            ("2PT", "Two-Point Conversion"),
                            ("SFTY", "Safety"),
                            ("D-TD", "Defensive Touchdown"),
                        ],
                        max_length=5,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("home_score_after", models.IntegerField(default=0)),
                ("away_score_after", models.IntegerField(default=0)),
                ("sequence", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_plays",
                        to="redzone.game",
                    ),
                ),
                (
                    "play",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="redzone.play",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="redzone.team"
                    ),
                ),
            ],
            options={
                "ordering": ["game", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gsis_id",
                    models.CharField(
                        db_index=True,
                        help_text="nflverse primary ID, e.g. '00-0033873'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("espn_id", models.CharField(blank=True, db_index=True, max_length=20)),
                ("pfr_id", models.CharField(blank=True, max_length=20)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=80)),
                ("short_name", models.CharField(blank=True, max_length=30)),
                ("jersey_number", models.CharField(blank=True, max_length=3)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("QB", "Quarterback"),
                            ("RB", "Running Back"),
                            ("FB", "Fullback"),
                            ("WR", "Wide Receiver"),
                            ("TE", "Tight End"),
                            ("OL", "Offensive Line"),
                            ("C", "Center"),
                            ("G", "Guard"),
                            ("T", "Tackle"),
                            ("K", "Kicker"),
                            ("P", "Punter"),
                            ("LS", "Long Snapper"),
                            ("DL", "Defensive Line"),
                            ("DE", "Defensive End"),
                            ("DT", "Defensive Tackle"),
                            ("LB", "Linebacker"),
                            ("OLB", "Outside Linebacker"),
                            ("ILB", "Inside Linebacker"),
                            ("MLB", "Middle Linebacker"),
                            ("CB", "Cornerback"),
                            ("S", "Safety"),
                            ("FS", "Free Safety"),
                            ("SS", "Strong Safety"),
                            ("DB", "Defensive Back"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "position_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QB", "Quarterback"),
                            ("RB", "Running Back"),
                            ("WR", "Wide Receiver"),
                            ("TE", "Tight End"),
                            ("OL", "Offensive Line"),
                            ("DL", "Defensive Line"),
                            ("LB", "Linebacker"),
                            ("DB", "Defensive Back"),
                            ("SPEC", "Special Teams"),
                        ],
                        max_length=5,
                    ),
                ),
                ("headshot_url", models.URLField(blank=True, max_length=500)),
                ("height", models.CharField(blank=True, max_length=10)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("college", models.CharField(blank=True, max_length=60)),
                ("draft_year", models.IntegerField(blank=True, null=True)),
                ("draft_round", models.IntegerField(blank=True, null=True)),
                ("draft_pick", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="redzone.team",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="GameLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("passing", "Passing"),
                            ("rushing", "Rushing"),
                            ("receiving", "Receiving"),
                        ],
                        max_length=15,
                    ),
                ),
                ("athlete_espn_id", models.CharField(blank=True, max_length=20)),
                ("athlete_name", models.CharField(max_length=80)),
                ("athlete_headshot_url", models.URLField(blank=True, max_length=500)),
                ("athlete_jersey", models.CharField(blank=True, max_length=3)),
                ("athlete_position", models.CharField(blank=True, max_length=5)),
                ("display_value", models.CharField(max_length=50)),
                ("stat_value", models.FloatField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaders",
                        to="redzone.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="redzone.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="redzone.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamGameStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.IntegerField()),
                ("week", models.IntegerField()),
                ("is_home", models.BooleanField()),
                ("total_yards", models.IntegerField(default=0)),
                ("total_plays", models.IntegerField(default=0)),
                ("first_downs", models.IntegerField(default=0)),
                ("first_downs_passing", models.IntegerField(default=0)),
                ("first_downs_rushing", models.IntegerField(default=0)),
                ("first_downs_penalty", models.IntegerField(default=0)),
                ("third_down_attempts", models.IntegerField(default=0)),
                ("third_down_conversions", models.IntegerField(default=0)),
                ("fourth_down_attempts", models.IntegerField(default=0)),
                ("fourth_down_conversions", models.IntegerField(default=0)),
                ("redzone_attempts", models.IntegerField(default=0)),
                ("redzone_scores", models.IntegerField(default=0)),
                ("pass_completions", models.IntegerField(default=0)),
                ("pass_attempts", models.IntegerField(default=0)),
                ("pass_yards", models.IntegerField(default=0)),
                ("pass_tds", models.IntegerField(default=0)),
                ("pass_ints", models.IntegerField(default=0)),
                ("sacks_allowed", models.IntegerField(default=0)),
                ("sack_yards_allowed", models.IntegerField(default=0)),
                ("passer_rating", models.FloatField(blank=True, null=True)),
                ("rush_attempts", models.IntegerField(default=0)),
                ("rush_yards", models.IntegerField(default=0)),
                ("rush_tds", models.IntegerField(default=0)),
                ("turnovers", models.IntegerField(default=0)),
                ("fumbles_lost", models.IntegerField(default=0)),
                ("interceptions_lost", models.IntegerField(default=0)),
                ("sacks_made", models.FloatField(default=0)),
                ("takeaways", models.IntegerField(default=0)),
                ("interceptions_caught", models.IntegerField(default=0)),
                ("fumbles_recovered", models.IntegerField(default=0)),
                ("defensive_tds", models.IntegerField(default=0)),
                ("punt_return_yards", models.IntegerField(default=0)),
                ("kick_return_yards", models.IntegerField(default=0)),
                ("return_tds", models.IntegerField(default=0)),
                ("penalties", models.IntegerField(default=0)),
                ("penalty_yards", models.IntegerField(default=0)),
                ("time_of_possession", models.CharField(blank=True, max_length=10)),
                ("time_of_possession_seconds", models.IntegerField(default=0)),
                ("points_scored", models.IntegerField(default=0)),
                ("points_allowed", models.IntegerField(default=0)),
                ("offensive_epa", models.FloatField(blank=True, null=True)),
                ("defensive_epa", models.FloatField(blank=True, null=True)),
                ("passing_epa", models.FloatField(blank=True, null=True)),
                ("rushing_epa", models.FloatField(blank=True, null=True)),
                ("fantasy_dst_points", models.FloatField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_stats",
                        to="redzone.game",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="redzone.team",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="redzone.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-season_year", "-week"],
            },
        ),
        migrations.CreateModel(
            name="TeamLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("dark", "Dark Background"),
                            ("scoreboard", "Scoreboard"),
                            ("scoreboard-dark", "Scoreboard Dark"),
                        ],
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logos",
                        to="redzone.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaybookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "delay_seconds",
                    models.FloatField(
                        default=5.0,
                        help_text="Seconds to wait before broadcasting this play.",
                    ),
                ),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="redzone.play"
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="redzone.playbook",
                    ),
                ),
            ],
            options={
                "ordering": ["playbook", "sequence"],
                "unique_together": {("playbook", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="PlayerGameStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.IntegerField()),
                ("week", models.IntegerField()),
                ("season_type", models.CharField(default="REG", max_length=4)),
                ("completions", models.IntegerField(default=0)),
                ("pass_attempts", models.IntegerField(default=0)),
                ("passing_yards", models.IntegerField(default=0)),
                ("passing_tds", models.IntegerField(default=0)),
                ("interceptions_thrown", models.IntegerField(default=0)),
                ("sacks_taken", models.IntegerField(default=0)),
                ("sack_yards_lost", models.IntegerField(default=0)),
                ("sack_fumbles", models.IntegerField(default=0)),
                ("sack_fumbles_lost", models.IntegerField(default=0)),
                ("passing_air_yards", models.IntegerField(default=0)),
                ("passing_yards_after_catch", models.IntegerField(default=0)),
                ("passing_first_downs", models.IntegerField(default=0)),
                ("passing_2pt_conversions", models.IntegerField(default=0)),
                ("passing_epa", models.FloatField(blank=True, null=True)),
                ("passer_rating", models.FloatField(blank=True, null=True)),
                ("qbr", models.FloatField(blank=True, null=True)),
                ("carries", models.IntegerField(default=0)),
                ("rushing_yards", models.IntegerField(default=0)),
                ("rushing_tds", models.IntegerField(default=0)),
                ("rushing_fumbles", models.IntegerField(default=0)),
                ("rushing_fumbles_lost", models.IntegerField(default=0)),
                ("rushing_first_downs", models.IntegerField(default=0)),
                ("rushing_2pt_conversions", models.IntegerField(default=0)),
                ("rushing_epa", models.FloatField(blank=True, null=True)),
                ("rushing_long", models.IntegerField(default=0)),
                ("receptions", models.IntegerField(default=0)),
                ("targets", models.IntegerField(default=0)),
                ("receiving_yards", models.IntegerField(default=0)),
                ("receiving_tds", models.IntegerField(default=0)),
                ("receiving_fumbles", models.IntegerField(default=0)),
                ("receiving_fumbles_lost", models.IntegerField(default=0)),
                ("receiving_air_yards", models.IntegerField(default=0)),
                ("receiving_yards_after_catch", models.IntegerField(default=0)),
                ("receiving_first_downs", models.IntegerField(default=0)),
                ("receiving_2pt_conversions", models.IntegerField(default=0)),
                ("receiving_epa", models.FloatField(blank=True, null=True)),
                ("receiving_long", models.IntegerField(default=0)),
                ("target_share", models.FloatField(blank=True, null=True)),
                ("air_yards_share", models.FloatField(blank=True, null=True)),
                ("wopr", models.FloatField(blank=True, null=True)),
                ("tackles_total", models.IntegerField(default=0)),
                ("tackles_solo", models.IntegerField(default=0)),
                ("tackles_assists", models.IntegerField(default=0)),
                ("tackles_for_loss", models.FloatField(default=0)),
                ("sacks_made", models.FloatField(default=0)),
                ("qb_hits", models.IntegerField(default=0)),
                ("passes_defended", models.IntegerField(default=0)),
                ("interceptions_caught", models.IntegerField(default=0)),
                ("interception_yards", models.IntegerField(default=0)),
                ("interception_tds", models.IntegerField(default=0)),
                ("forced_fumbles", models.IntegerField(default=0)),
                ("fumble_recoveries", models.IntegerField(default=0)),
                ("defensive_tds", models.IntegerField(default=0)),
                ("safeties", models.IntegerField(default=0)),
                ("blocked_kicks", models.IntegerField(default=0)),
                ("kick_return_attempts", models.IntegerField(default=0)),
                ("kick_return_yards", models.IntegerField(default=0)),
                ("kick_return_tds", models.IntegerField(default=0)),
                ("punt_return_attempts", models.IntegerField(default=0)),
                ("punt_return_yards", models.IntegerField(default=0)),
                ("punt_return_tds", models.IntegerField(default=0)),
                ("special_teams_tds", models.IntegerField(default=0)),
                ("fg_attempts", models.IntegerField(default=0)),
                ("fg_made", models.IntegerField(default=0)),
                ("fg_long", models.IntegerField(default=0)),
                ("fg_made_0_19", models.IntegerField(default=0)),
                ("fg_made_20_29", models.IntegerField(default=0)),
                ("fg_made_30_39", models.IntegerField(default=0)),
                ("fg_made_40_49", models.IntegerField(default=0)),
                ("fg_made_50_59", models.IntegerField(default=0)),
                ("fg_made_60_plus", models.IntegerField(default=0)),
                ("pat_attempts", models.IntegerField(default=0)),
                ("pat_made", models.IntegerField(default=0)),
                ("pat_missed", models.IntegerField(default=0)),
                ("punt_attempts", models.IntegerField(default=0)),
                ("punt_yards", models.IntegerField(default=0)),
                ("punt_long", models.IntegerField(default=0)),
                ("punt_inside_20", models.IntegerField(default=0)),
                ("punt_touchbacks", models.IntegerField(default=0)),
                ("fantasy_points_standard", models.FloatField(blank=True, null=True)),
                ("fantasy_points_ppr", models.FloatField(blank=True, null=True)),
                ("fantasy_points_half_ppr", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="redzone.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="redzone.player",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="redzone.team",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="redzone.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-season_year", "-week"],
                "indexes": [
                    models.Index(
                        fields=["game", "team"], name="redzone_pla_game_id_ff111c_idx"
                    ),
                    models.Index(
                        fields=["player", "season_year", "week"],
                        name="redzone_pla_player__1139e9_idx",
                    ),
                    models.Index(
                        fields=["season_year", "week", "fantasy_points_ppr"],
                        name="redzone_pla_season__6365c0_idx",
                    ),
                ],
                "unique_together": {("player", "game")},
            },
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["current_team", "position"],
                name="redzone_pla_current_f361e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["game", "sequence"], name="redzone_pla_game_id_fc66cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["game", "quarter"], name="redzone_pla_game_id_6ae344_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["possession_team"], name="redzone_pla_possess_f180e4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="play",
            unique_together={("game", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="gameleader",
            unique_together={("game", "team", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="drive",
            unique_together={("game", "drive_number")},
        ),
        migrations.AddIndex(
            model_name="teamgamestats",
            index=models.Index(
                fields=["team", "season_year"], name="redzone_tea_team_id_9ac3c3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamgamestats",
            unique_together={("team", "game")},
        ),
        migrations.AlterUniqueTogether(
            name="teamlogo",
            unique_together={("team", "logo_type")},
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["season", "week"], name="redzone_gam_season__4a19fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["status"], name="redzone_gam_status_b47c66_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["game_date"], name="redzone_gam_game_da_ab1e54_idx"
            ),
        ),
    ]
