# Generated by Django 5.2.11 on 2026-02-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redzone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("all", "All Platforms"),
                            ("twitter", "Twitter / X"),
                            ("instagram", "Instagram"),
                            ("bluesky", "Bluesky"),
                            ("threads", "Threads"),
                        ],
                        default="all",
                        max_length=15,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Hashtag without # (e.g. 'SEAvsNE', 'SuperBowl')",
                        max_length=100,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="The main game hashtag (e.g. #SEAvsNE)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("espn_team", "ESPN Team News API"),
                            ("espn_player", "ESPN Player News API"),
                            ("espn_league", "ESPN League News API"),
                            ("rss", "RSS Feed"),
                            ("reddit", "Reddit Subreddit"),
                            ("twitter_list", "Twitter/X List"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("league", "League-wide"),
                            ("team", "Team-specific"),
                            ("player", "Player-specific"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "url_template",
                    models.CharField(
                        help_text="URL with placeholders: {team_id}, {player_id}, {espn_id}. e.g. 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/news?team={espn_id}'",
                        max_length=500,
                    ),
                ),
                (
                    "cache_ttl_seconds",
                    models.IntegerField(
                        default=300,
                        help_text="How long to cache results in Redis (seconds)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=10,
                        help_text="Lower = higher priority. Controls display order.",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlayerCollegeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college", models.CharField(max_length=80)),
                ("conference", models.CharField(blank=True, max_length=30)),
                (
                    "start_year",
                    models.IntegerField(
                        blank=True, help_text="First year at this school", null=True
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        blank=True, help_text="Last year at this school", null=True
                    ),
                ),
                (
                    "is_redshirt",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the player redshirted at this school",
                    ),
                ),
                (
                    "redshirt_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Which year was the redshirt year, if known",
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="True for the school they were drafted from / last attended",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Order of schools: 1=first, 2=transfer, etc.",
                    ),
                ),
            ],
            options={
                "ordering": ["player", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PlayerCombine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.IntegerField(
                        help_text="Combine year (typically draft year)"
                    ),
                ),
                (
                    "position",
                    models.CharField(help_text="Position at combine", max_length=5),
                ),
                ("height_inches", models.FloatField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                (
                    "arm_length",
                    models.FloatField(
                        blank=True, help_text="Arm length in inches", null=True
                    ),
                ),
                (
                    "hand_size",
                    models.FloatField(
                        blank=True, help_text="Hand size in inches", null=True
                    ),
                ),
                (
                    "wingspan",
                    models.FloatField(
                        blank=True, help_text="Wingspan in inches", null=True
                    ),
                ),
                (
                    "forty_yard",
                    models.FloatField(
                        blank=True, help_text="40-yard dash in seconds", null=True
                    ),
                ),
                (
                    "twenty_yard_split",
                    models.FloatField(
                        blank=True, help_text="20-yard split in seconds", null=True
                    ),
                ),
                (
                    "ten_yard_split",
                    models.FloatField(
                        blank=True, help_text="10-yard split in seconds", null=True
                    ),
                ),
                (
                    "bench_press",
                    models.IntegerField(
                        blank=True, help_text="225lb bench press reps", null=True
                    ),
                ),
                (
                    "vertical_jump",
                    models.FloatField(
                        blank=True, help_text="Vertical jump in inches", null=True
                    ),
                ),
                (
                    "broad_jump",
                    models.IntegerField(
                        blank=True, help_text="Broad jump in inches", null=True
                    ),
                ),
                (
                    "three_cone",
                    models.FloatField(
                        blank=True, help_text="3-cone drill in seconds", null=True
                    ),
                ),
                (
                    "shuttle",
                    models.FloatField(
                        blank=True, help_text="20-yard shuttle in seconds", null=True
                    ),
                ),
                ("draft_round", models.IntegerField(blank=True, null=True)),
                ("draft_overall", models.IntegerField(blank=True, null=True)),
                ("pfr_url", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-season"],
            },
        ),
        migrations.CreateModel(
            name="PlayerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("year_signed", models.IntegerField()),
                (
                    "years",
                    models.IntegerField(help_text="Total contract length in years"),
                ),
                (
                    "total_value",
                    models.BigIntegerField(help_text="Total contract value in dollars"),
                ),
                (
                    "apy",
                    models.BigIntegerField(help_text="Average per year in dollars"),
                ),
                (
                    "guaranteed",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total guaranteed money in dollars",
                        null=True,
                    ),
                ),
                (
                    "apy_cap_pct",
                    models.FloatField(
                        blank=True,
                        help_text="APY as percentage of salary cap at signing",
                        null=True,
                    ),
                ),
                ("inflated_value", models.BigIntegerField(blank=True, null=True)),
                ("inflated_apy", models.BigIntegerField(blank=True, null=True)),
                ("inflated_guaranteed", models.BigIntegerField(blank=True, null=True)),
                (
                    "year_details",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Per-year breakdown: cap hit, base salary, bonuses, dead cap",
                    ),
                ),
                ("otc_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year_signed"],
            },
        ),
        migrations.CreateModel(
            name="PlayerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("drafted", "Drafted"),
                            ("signed", "Signed"),
                            ("signed_ps", "Signed to Practice Squad"),
                            ("traded", "Traded"),
                            ("released", "Released"),
                            ("waived", "Waived"),
                            ("waived_injured", "Waived/Injured"),
                            ("ir", "Placed on IR"),
                            ("ir_return", "Returned from IR"),
                            ("pup", "Placed on PUP"),
                            ("suspended", "Suspended"),
                            ("reinstated", "Reinstated"),
                            ("retired", "Retired"),
                            ("unretired", "Unretired"),
                            ("claimed", "Claimed off Waivers"),
                            ("promoted", "Promoted from Practice Squad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("season", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter / X"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("threads", "Threads"),
                            ("bluesky", "Bluesky"),
                            ("snapchat", "Snapchat"),
                            ("linkedin", "LinkedIn"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("pr", "Press / Communications"),
                            ("spanish", "Spanish Language"),
                            ("cheerleaders", "Cheerleaders / Dance Team"),
                            ("mascot", "Mascot"),
                            ("personal", "Personal"),
                            ("fan", "Fan Account"),
                        ],
                        default="official",
                        max_length=15,
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        help_text="Username/handle without @ (e.g. 'Seahawks')",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["platform", "account_type"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="college_conference",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="player",
            name="depth_chart_position",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="player",
            name="draft_overall",
            field=models.IntegerField(
                blank=True, help_text="Overall pick number (1-262)", null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="draft_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team that originally drafted this player",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafted_players",
                to="redzone.team",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="entry_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year entered the league (may differ from draft year for UDFAs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="esb_id",
            field=models.CharField(
                blank=True, help_text="Elias Sports Bureau ID", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="height_inches",
            field=models.IntegerField(
                blank=True,
                help_text="Height in inches for sorting/filtering (76 = 6'4\")",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="is_undrafted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="last_roster_check",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time roster status / team was verified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="otc_id",
            field=models.CharField(
                blank=True, help_text="OverTheCap ID, for contract joins", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="pff_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="player",
            name="rookie_season",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACT", "Active"),
                    ("RES", "Reserve/Injured"),
                    ("INA", "Inactive"),
                    ("PUP", "PUP"),
                    ("SUS", "Suspended"),
                    ("NFI", "Non-Football Injury"),
                    ("EXE", "Exempt"),
                    ("UFA", "Unrestricted Free Agent"),
                    ("RFA", "Restricted Free Agent"),
                    ("RET", "Retired"),
                    ("CUT", "Released"),
                    ("PRA", "Practice Squad"),
                ],
                help_text="Current roster status from nflverse",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="rotowire_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="player",
            name="smart_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="player",
            name="sportradar_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="player",
            name="suffix",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="player",
            name="yahoo_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="player",
            name="years_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="college",
            field=models.CharField(
                blank=True,
                help_text="Last/primary college. Full history in PlayerCollegeHistory.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="draft_pick",
            field=models.IntegerField(
                blank=True, help_text="Pick within the round", null=True
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="pfr_id",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("QB", "Quarterback"),
                    ("RB", "Running Back"),
                    ("FB", "Fullback"),
                    ("WR", "Wide Receiver"),
                    ("TE", "Tight End"),
                    ("OL", "Offensive Line"),
                    ("C", "Center"),
                    ("G", "Guard"),
                    ("T", "Tackle"),
                    ("K", "Kicker"),
                    ("P", "Punter"),
                    ("LS", "Long Snapper"),
                    ("DL", "Defensive Line"),
                    ("DE", "Defensive End"),
                    ("DT", "Defensive Tackle"),
                    ("NT", "Nose Tackle"),
                    ("LB", "Linebacker"),
                    ("OLB", "Outside Linebacker"),
                    ("ILB", "Inside Linebacker"),
                    ("MLB", "Middle Linebacker"),
                    ("CB", "Cornerback"),
                    ("S", "Safety"),
                    ("FS", "Free Safety"),
                    ("SS", "Strong Safety"),
                    ("DB", "Defensive Back"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["draft_year"], name="redzone_pla_draft_y_db931d_idx"
            ),
        ),
        migrations.AddField(
            model_name="gamehashtag",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hashtags",
                to="redzone.game",
            ),
        ),
        migrations.AddField(
            model_name="newssource",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_sources",
                to="redzone.team",
            ),
        ),
        migrations.AddField(
            model_name="playercollegehistory",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="college_history",
                to="redzone.player",
            ),
        ),
        migrations.AddField(
            model_name="playercombine",
            name="draft_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="redzone.team",
            ),
        ),
        migrations.AddField(
            model_name="playercombine",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="combine_results",
                to="redzone.player",
            ),
        ),
        migrations.AddField(
            model_name="playercontract",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="redzone.player",
            ),
        ),
        migrations.AddField(
            model_name="playercontract",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team the contract is with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="redzone.team",
            ),
        ),
        migrations.AddField(
            model_name="playertransaction",
            name="from_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_transactions",
                to="redzone.team",
            ),
        ),
        migrations.AddField(
            model_name="playertransaction",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="redzone.player",
            ),
        ),
        migrations.AddField(
            model_name="playertransaction",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Links both sides of a trade",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="redzone.playertransaction",
            ),
        ),
        migrations.AddField(
            model_name="playertransaction",
            name="to_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_transactions",
                to="redzone.team",
            ),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_accounts",
                to="redzone.player",
            ),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_accounts",
                to="redzone.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamehashtag",
            unique_together={("game", "platform", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="playercollegehistory",
            unique_together={("player", "college", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="playercombine",
            unique_together={("player", "season")},
        ),
        migrations.AddIndex(
            model_name="playercontract",
            index=models.Index(
                fields=["player", "is_active"], name="redzone_pla_player__394ead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playertransaction",
            index=models.Index(
                fields=["player", "-date"], name="redzone_pla_player__ebaf4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playertransaction",
            index=models.Index(fields=["date"], name="redzone_pla_date_1ddf3c_idx"),
        ),
        migrations.AddIndex(
            model_name="playertransaction",
            index=models.Index(
                fields=["to_team", "date"], name="redzone_pla_to_team_68e9a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["team", "platform"], name="redzone_soc_team_id_573bcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["player", "platform"], name="redzone_soc_player__ad0d5c_idx"
            ),
        ),
    ]
