# Generated by Django 5.2.10 on 2026-02-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competency",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
