# Generated by Django 5.2.10 on 2026-02-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_competency_description"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="artifact",
            name="core_artifa_status_a76bd5_idx",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="complexity",
        ),
        migrations.AddField(
            model_name="artifact",
            name="domain",
            field=models.CharField(
                choices=[
                    ("football", "Football Platform"),
                    ("atlas", "Engineering Atlas"),
                    ("infrastructure", "Infrastructure"),
                ],
                default="atlas",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["status", "domain"], name="core_artifa_status_c6cf3c_idx"
            ),
        ),
    ]
