# Generated by Django 5.2.11 on 2026-02-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_artifact_core_artifa_status_a76bd5_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="domain",
            field=models.CharField(
                choices=[
                    ("football", "Project Gridstream"),
                    ("atlas", "Engineering Atlas"),
                    ("infrastructure", "Infrastructure"),
                ],
                default="atlas",
                max_length=50,
            ),
        ),
    ]
