[package]
name = "nflreadrust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

# HTTP Client (with stream support for large files)
reqwest = { version = "0.11", features = ["stream", "rustls-tls"] }

serde_json = "1.0"
parquet = { version = "54.2.1", features = ["json"] }

# Database (Postgres)
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "postgres", "chrono", "json"] }

anyhow = "1.0"
futures-util = "0.3.31"
chrono = "0.4.43"
sha2 = "0.10"
