
FROM node:20-alpine as base

RUN corepack enable && corepack prepare pnpm@latest --activate

FROM base as deps

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web-next/package.json ./apps/web-next/

RUN pnpm install --frozen-lockfile

FROM base as development

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/web-next/node_modules ./apps/web-next/node_modules
COPY . .

WORKDIR /app/apps/web-next

EXPOSE 3000

CMD ["pnpm", "dev", "--hostname", "0.0.0.0"]