FROM rust:latest

WORKDIR /app

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/* \
    && rustup component add rustfmt 

COPY . .

WORKDIR /app/nflreadrust

RUN cargo build

EXPOSE 8001

CMD ["cargo", "run"]