FROM golang:1.25-rc-alpine

RUN apk add --no-cache curl \
  && go install github.com/air-verse/air@latest \
  && go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.63.4

WORKDIR /app/gridstream

COPY gridstream/go.mod ./

RUN go mod download

COPY gridstream/ .

EXPOSE 8002

CMD ["air", \
    "--build.cmd", "go build -o bin/main ./cmd/gridstream", \
    "--build.entrypoint", "./bin/main", \
    "--build.exclude_dir", "bin"]