import type { PlayAnimationData } from '@atlas/sdk/gridstream/types';

export interface PlayAnimationScenario {
  id: string;
  label: string;
  awayAbbr: string;
  play: PlayAnimationData;
}

const BASE_PLAY: PlayAnimationData = {
  type: 'pass',
  direction: 'middle',
  offenseTeam: 'SEA',
  startDistance: 10,
  fromYardline: 45,
  fromSide: 'SEA',
  toYardline: 45,
  toSide: 'SEA',
  yardsGained: 0,
  isComplete: true,
  isFirstDown: false,
  isTurnover: false,
  description: 'Test play',
};

function makePlay(overrides: Partial<PlayAnimationData>): PlayAnimationData {
  return {
    ...BASE_PLAY,
    ...overrides,
    description: overrides.description ?? BASE_PLAY.description,
  };
}

export const PLAY_ANIMATION_SCENARIOS: PlayAnimationScenario[] = [
  {
    id: 'pass-complete-right',
    label: 'Complete pass right',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'pass',
      direction: 'right',
      fromYardline: 41,
      fromSide: 'NE',
      toYardline: 28,
      toSide: 'NE',
      yardsGained: 13,
      isComplete: true,
      isFirstDown: true,
      description: 'D.Maye pass short right to T.Henry for 13 yards.',
      actor: {
        name: 'T.Henry',
        summary: '13 Yard Catch',
        lines: ['2 Catches - 25 Yards'],
      },
      qbActor: {
        name: 'D.Maye',
        summary: '13 Yard Pass',
        lines: ['12/18 Passing - 142 Yards'],
      },
    }),
  },
  {
    id: 'pass-incomplete-left',
    label: 'Incomplete pass left',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'pass',
      direction: 'left',
      fromYardline: 18,
      fromSide: 'SEA',
      toYardline: 18,
      toSide: 'SEA',
      yardsGained: 0,
      isComplete: false,
      description: 'S.Darnold pass incomplete short left.',
      qbActor: {
        name: 'S.Darnold',
        summary: 'Incomplete Pass',
        lines: ['15/21 Passing - 179 Yards'],
      },
    }),
  },
  {
    id: 'rush-middle',
    label: 'Rush up middle',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'rush',
      direction: 'middle',
      fromYardline: 34,
      fromSide: 'NE',
      toYardline: 29,
      toSide: 'NE',
      yardsGained: 5,
      isComplete: true,
      description: 'K.Walker up the middle for 5 yards.',
      actor: {
        name: 'K.Walker',
        summary: '5 Yard Rush',
        lines: ['6 Rushes - 39 Yards'],
      },
    }),
  },
  {
    id: 'sack-loss',
    label: 'Sack for loss',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'pass',
      direction: 'middle',
      fromYardline: 28,
      fromSide: 'NE',
      toYardline: 33,
      toSide: 'NE',
      yardsGained: -5,
      isComplete: false,
      description: 'D.Maye sacked at NE 33 for -5 yards.',
      qbActor: {
        name: 'D.Maye',
        summary: '-5 Yard Sack',
        lines: ['17/30 Passing - 214 Yards', '3 Sacks'],
      },
    }),
  },
  {
    id: 'turnover-interception-return',
    label: 'Interception with return',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'turnover',
      direction: 'left',
      fromYardline: 44,
      fromSide: 'NE',
      turnoverSpotYardline: 27,
      turnoverSpotSide: 'SEA',
      toYardline: 38,
      toSide: 'NE',
      yardsGained: 35,
      isComplete: false,
      isTurnover: true,
      turnoverBy: 'SEA',
      description: 'Pass intercepted by J.Love at SEA 27, returned to NE 38.',
      actor: {
        name: 'J.Love',
        summary: '35 Yard Return',
        lines: ['1 INT - 35 Return Yards'],
      },
    }),
  },
  {
    id: 'kickoff-touchback',
    label: 'Kickoff touchback',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'kick',
      direction: 'middle',
      fromYardline: 35,
      fromSide: 'SEA',
      kickLandingYardline: 0,
      kickLandingSide: 'NE',
      toYardline: 30,
      toSide: 'NE',
      yardsGained: 0,
      description: 'Kicker kicks 65 yards to end zone, touchback.',
      actor: null,
    }),
  },
  {
    id: 'kickoff-return',
    label: 'Kickoff return',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'kick',
      direction: 'middle',
      fromYardline: 35,
      fromSide: 'SEA',
      kickLandingYardline: 6,
      kickLandingSide: 'NE',
      toYardline: 31,
      toSide: 'SEA',
      yardsGained: 25,
      description: 'Kickoff to NE 6, returned 25 yards to SEA 31.',
      actor: {
        name: 'R.Shaheed',
        summary: '25 Yard Return',
        lines: ['2 Returns - 47 Yards'],
      },
    }),
  },
  {
    id: 'punt-out-of-bounds',
    label: 'Punt out of bounds',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'kick',
      direction: 'right',
      fromYardline: 42,
      fromSide: 'SEA',
      kickLandingYardline: 6,
      kickLandingSide: 'NE',
      toYardline: 6,
      toSide: 'NE',
      yardsGained: 52,
      description: 'Punter punts 52 yards to NE 6, out of bounds.',
      actor: null,
    }),
  },
  {
    id: 'field-goal-good',
    label: 'Field goal good',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'fieldgoal',
      direction: 'middle',
      fromYardline: 24,
      fromSide: 'NE',
      toYardline: 0,
      toSide: 'NE',
      yardsGained: 0,
      fgDistance: 41,
      fgResult: 'made',
      description: 'Field goal is GOOD from 41 yards.',
      actor: {
        name: 'J.Myers',
        summary: 'FG GOOD',
        lines: ['2/2 FG'],
      },
    }),
  },
  {
    id: 'field-goal-miss-right',
    label: 'Field goal wide right',
    awayAbbr: 'SEA',
    play: makePlay({
      type: 'fieldgoal',
      direction: 'middle',
      fromYardline: 31,
      fromSide: 'NE',
      toYardline: 0,
      toSide: 'NE',
      yardsGained: 0,
      fgDistance: 49,
      fgResult: 'wide_right',
      description: '49-yard field goal is NO GOOD, wide right.',
      actor: {
        name: 'J.Myers',
        summary: 'FG NO GOOD',
        lines: ['1/2 FG'],
      },
    }),
  },
];
